That one was because we weren't initializing the static var.
actually this is the real error:
duplicate symbol __ZN4stan4math7ADStack8instanceE in:
    /var/folders/l1/1s2p_0cn52z0xd93f1c9p2m80000gn/T/two-4ed2fc.o
    one.o
ld: 1 duplicate symbol for architecture x86_64